### ISSUE TITLE
Is there any plans to release the model weights and data?

### ISSUE THREAD

**Issue by trouble-maker007** [yuli0103/CGB-DM#1]

**Comment by yuli0103** [comment]
We plan to release them soon.

**Comment by marvin521** [comment]
Everyone is eagerly awaiting

**Comment by yuli0103** [comment]
Following the experimental setup outlined in the paper, you should be able to achieve similar results. 
We will continue to refine and update this project when the paper is accepted. Future updates will include a more comprehensive version of the paper and enhanced pretrain weights. 
Thank you for your interest, and please stay tuned for upcoming developments.
