### ISSUE TITLE
how to generate the img_sal_sub image path list, I cannot found any code about generate?

### ISSUE THREAD

**Issue by trouble-maker007** [yuli0103/CGB-DM#2]
img_sal = Image.open(self.sal[idx]).convert("L")
img_sal_sub = Image.open(self.sal_sub[idx]).convert("L")
img_sal_map = Image.fromarray(np.maximum(np.array(img_sal), np.array(img_sal_sub)))

@yuli0103 I could not find any code about how to generate the image about the `saliency_sub`, would you like to give more detail about how to preprocess? Does use two model(ISNet and BASNet) to generate saliency detection result
I was tried to preprocess the cgl data into your training format, but still have no idea to get the `saliency_sub ` data.

<img width="829" alt="image" src="https://github.com/user-attachments/assets/fad3f4aa-d8e6-460a-8158-5c45a3a4c437">

**Comment by trouble-maker007** [comment]
null

**Comment by yuli0103** [comment]
> img_sal = Image.open(self.sal[idx]).convert("L") img_sal_sub = Image.open(self.sal_sub[idx]).convert("L") img_sal_map = Image.fromarray(np.maximum(np.array(img_sal), np.array(img_sal_sub)))
> 
> @yuli0103 I could not find any code about how to generate the image about the `saliency_sub`, would you like to give more detail about how to preprocess? Does use two model(ISNet and BASNet) to generate saliency detection result I was tried to preprocess the cgl data into your training format, but still have no idea to get the `saliency_sub ` data.
> 
> <img alt="image" width="829" src="https://private-user-images.githubusercontent.com/73164596/352082677-fad3f4aa-d8e6-460a-8158-5c45a3a4c437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwODkzMDIsIm5iZiI6MTcyMjA4OTAwMiwicGF0aCI6Ii83MzE2NDU5Ni8zNTIwODI2NzctZmFkM2Y0YWEtZDhlNi00NjBhLTgxNTgtNWM0NWEzYTRjNDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE0MDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MWRlNDdlZWUwMmZhNTdmMDFiM2Y2ZDk5NzQ3YTI0ZTk5MDc1MmVmODQxZWEwZDVlOGVjYmU2OTAyN2VkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssNZTpRuZo6dw9q8ho6R8zOoxtjJZpwICfLC1Anf9UY">

I apologize for the inconvenience. In our setup, images in the 'saliency' directory are generated using the ISNet model, while images in the 'saliency_sub' directory are generated using the BASNet model. You can find the specific code in `data_process/saliency_detection.py`. Furthermore, I have updated the latest code package and dataset link.

**Comment by trouble-maker007** [comment]
@yuli0103 Thank you for your reply.I will try to train under this setting.

**Comment by trouble-maker007** [comment]
@yuli0103 Does run single image support condition layout generate, such as cwh

**Comment by yuli0103** [comment]
> @yuli0103 Does run single image support condition layout generate, such as cwh

Thank you for your suggestion. Going forward, I will support condition layout generation in "run_single_image.py".

**Comment by trouble-maker007** [comment]
@yuli0103 thanks for the response, I set batch 1 in test.py
